/** Independent PC03B authoring. No execution until root supplies a frozen snapshot and exact binary SHA. */
import { expect, request, test, type APIRequestContext, type Browser, type BrowserContext, type Page } from "@playwright/test";
import { apiLogin, loginViaUi, seedPhoto } from "./helpers";
import { waitForJob } from "./job-recovery-harness";
import { Pc03bQaBackend, PASSWORD, WEB, attach, saveEvidence } from "./qa-pc03b-backend";
import { bindOriginal, businessCounts, confirmQuote, makePublishable, publish, readQuote, seedDraft, seedQuote, submitQuote, summaries } from "./qa-pc03b-fixture";

let b: Pc03bQaBackend, api: APIRequestContext;
const contexts: BrowserContext[] = [];
test.describe.configure({ mode: "default", timeout: 150000 });
test.beforeAll(async () => { b = new Pc03bQaBackend(); await b.start(); api = await request.newContext(); });
test.afterEach(async () => { for (const c of contexts.splice(0)) await c.close(); });
test.afterAll(async () => { await api?.dispose(); await b?.cleanup(); });
async function open(browser: Browser, url: string, width = 375, backend = b) { const context = await browser.newContext({ viewport: { width, height: 950 } }); contexts.push(context); const page = await context.newPage(); page.setDefaultTimeout(15000); const state = await attach(page, backend); await loginViaUi(page, WEB, PASSWORD); await expect(page.locator(".workflow-actions__status").first()).not.toHaveText("正在读取处理状态…"); state.writes.length = 0; state.reads.length = 0; await page.goto(WEB + url); return { context, page, state }; }
const confirmPath = (q: Awaited<ReturnType<typeof seedQuote>>) => `/items/${q.itemId}/import/confirm?documentId=${q.documentId}&preparationId=${q.preparationId}&quoteId=${q.quote.id}`;
const generate = (p: Page) => p.getByTestId("generate-button");
async function consent(page: Page) { const c = page.getByRole("checkbox", { name: "我已阅读并确认将上述资料发送给对应供应商", exact: true }); await expect(c).toBeEnabled(); if (!(await c.isChecked())) await c.check(); await expect(page.getByTestId("confirmed-at")).toBeVisible(); await expect(generate(page)).toBeEnabled(); }
async function narrow(page: Page) { expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); }

test("QA PC3-006 one library batch, real priority/old release and read-error fallback on 375", async ({ browser }) => {
  const { ref, csrf } = await seedDraft(api, b, "PC03B library published history"); const ready = await makePublishable(api, b, ref, csrf); const r = await publish(api, b, ref, csrf, ready.etag); expect(r.status()).toBe(201); const releaseId = (await r.json()).data.id as string;
  // A stopped historical job is a labelled private status fixture, not a generated failure claim.
  b.db("UPDATE jobs SET status='failed' WHERE id=?", [ref.jobId]);
  for (let n = 0; n < 8; n++) expect((await api.post(b.base + "/api/v1/items", { headers: { "x-csrf-token": csrf }, data: { name: `PC03B visible batch ${n}`, model: "fake" } })).status()).toBe(201);
  const baseline = businessCounts(b); const { page, state } = await open(browser, "/"); const row = page.locator(".item-row").filter({ has: page.getByRole("link", { name: "PC03B library published history", exact: true }) });
  await expect(row.getByRole("link", { name: "处理任务", exact: true })).toHaveAttribute("href", `/jobs/${ref.jobId}`); await expect(row.getByRole("link", { name: "阅读已发布版", exact: true })).toHaveAttribute("href", `/items/${ref.itemId}/releases/${releaseId}`);
  expect(state.reads.filter(v => v.startsWith("/api/v1/items/summaries?"))).toHaveLength(1); expect(state.reads.filter(v => /\/items\/[^/?]+\/(jobs|drafts|releases)(\?|$)/.test(v) || /^\/api\/v1\/jobs\//.test(v))).toEqual([]); await narrow(page);
  await page.route("**/api/v1/items/summaries?*", async route => { const bad = await route.fetch({ url: b.base + "/api/v1/items/summaries?ids=00000000-0000-4000-8000-000000000099" }); expect(bad.status()).toBe(404); await route.fulfill({ response: bad }); });
  await page.reload(); await expect(row).toContainText("处理状态暂不可用"); await expect(row.getByRole("link", { name: "查看物品", exact: true })).toHaveAttribute("href", `/items/${ref.itemId}`); await expect(row.getByRole("link", { name: "处理任务", exact: true })).toHaveCount(0); expect(state.writes).toEqual([]); expect(businessCounts(b)).toEqual(baseline); expect(state.external + state.pageErrors).toBe(0);
  saveEvidence("browser-library", { ...ref, releaseId, rows: 9, noRowDetailRequests: true, real404Fallback: true, viewport: 375, noWrites: true });
});

test("QA PC3-007 wizard reflects missing/new/old originals, changed views and expired consent", async ({ browser }) => {
  const q = await seedQuote(api, b, "PC03B wizard facts"); await confirmQuote(api, b, q.itemId, q.csrf, q.quote.id); const baseline = businessCounts(b); const second = await bindOriginal(api, b, q);
  const { page, state } = await open(browser, confirmPath(q)); const steps = page.getByRole("list", { name: "新建向导步骤", exact: true });
  await expect(steps.locator('[aria-current="step"]')).toHaveText("预算/隐私确认"); await expect(steps.locator("li").filter({ hasText: "准备" })).toContainText("已完成");
  await page.getByLabel("所选原件", { exact: true }).selectOption(second.documentId); await expect(steps.locator("li").filter({ hasText: "准备" })).toContainText("需重新检查"); await expect(generate(page)).toBeDisabled();
  await page.getByLabel("所选原件", { exact: true }).selectOption(q.documentId); await expect(steps.locator("li").filter({ hasText: "准备" })).toContainText("已完成");
  const photoResponse = await api.get(`${b.base}/api/v1/items/${q.itemId}/photos`); const left = (await photoResponse.json()).data.find((p: { view: string }) => p.view === "left") as { id: string; revision: number }; expect((await api.patch(`${b.base}/api/v1/items/${q.itemId}/photos/${left.id}`, { headers: { "x-csrf-token": q.csrf, "if-match": `"r${left.revision}"` }, data: { view: "detail" } })).status()).toBe(200);
  await page.goto(WEB + confirmPath(q)); await expect(steps.locator("li").filter({ hasText: "视图排列" })).toContainText("需重新检查"); await expect(generate(page)).toBeDisabled();
  await seedPhoto(api, b.base, q.csrf, q.itemId, "right", "sample-photo-front.jpg"); await page.reload(); await expect(page.getByText("报价所用资料或配置已改变，需要重新获取报价并确认发送范围。", { exact: true })).toBeVisible(); await expect(generate(page)).toBeDisabled(); expect((await readQuote(api, b, q.itemId, q.quote.id)).inputIssue).toBe("inputChanged");
  await page.getByRole("button", { name: "重新获取报价", exact: true }).click(); await expect(page.getByTestId("quote-panel")).toBeVisible(); const checkbox = page.getByRole("checkbox", { name: "我已阅读并确认将上述资料发送给对应供应商", exact: true }); await expect(checkbox).not.toBeChecked(); await expect(generate(page)).toBeDisabled();
  const latest = (await summaries(api, b, [q.itemId], q.documentId))[0]!.latestQuoteId!; b.quoteClock(latest, 946684800000);
  await page.reload(); await expect(page.getByTestId("quote-expiry")).toHaveText("已过期"); await expect(steps.locator("li").filter({ hasText: "预算/隐私确认" })).toContainText("需重新检查"); await expect(generate(page)).toBeDisabled(); await narrow(page); expect(state.jobPosts).toHaveLength(0); expect(businessCounts(b)).toEqual(baseline); expect(state.external + state.pageErrors).toBe(0);
  saveEvidence("browser-wizard", { itemId: q.itemId, oldDocument: q.documentId, newDocument: second.documentId, newQuote: latest, realViewChange: true, newConsentRequired: true, expiredPrivateClockFixture: true, noJobsOrCost: true });
});

test("QA PC3-008 real accepted response dropped then fresh context restores exactly one job", async ({ browser }) => {
  const q = await seedQuote(api, b, "PC03B accepted response loss"); const { page, state } = await open(browser, confirmPath(q)); await consent(page); const counts = { ...b.fixture.counts }; let acceptedId: string | null = null; let denyQuote = false;
  await page.route(`**/api/v1/items/${q.itemId}/estimates/${q.quote.id}`, async route => { if (!denyQuote) { await route.fallback(); return; } const failed = await route.fetch({ url: `${b.base}/api/v1/items/${q.itemId}/estimates/00000000-0000-4000-8000-000000000099` }); expect(failed.status()).toBe(404); await route.fulfill({ response: failed }); });
  await page.route(`**/api/v1/items/${q.itemId}/jobs`, async route => { const r = await route.fetch({ url: `${b.base}/api/v1/items/${q.itemId}/jobs` }); expect(r.status()).toBe(202); acceptedId = (await r.json()).data.id as string; denyQuote = true; await route.abort("failed"); });
  await generate(page).click(); await expect(page.getByTestId("submission-recovery")).toContainText("结果待核对"); await expect(generate(page)).toBeDisabled(); await page.getByRole("button", { name: "重新核对结果", exact: true }).click(); await expect(page.getByTestId("submission-recovery")).toBeVisible(); expect(state.jobPosts).toHaveLength(1); expect(state.writes.filter(v => /POST .*\/estimates$/.test(v))).toEqual([]);
  expect(acceptedId).not.toBeNull(); const fresh = await open(browser, `/items/${q.itemId}/import/confirm`); expect(await fresh.page.evaluate(() => localStorage.length)).toBe(0); await expect(fresh.page.getByTestId("job-accepted")).toContainText(acceptedId!); await expect(fresh.page.getByRole("link", { name: "查看任务详情", exact: true })).toHaveAttribute("href", `/jobs/${acceptedId}`); expect(fresh.state.jobPosts).toHaveLength(0); expect(fresh.state.writes).toEqual([]);
  await waitForJob(api, b.base, acceptedId!, j => j.status === "succeeded", "PC03B exactly one accepted fake provider run", 90000); expect(b.db("SELECT count(*) AS count FROM jobs WHERE item_id=?", [q.itemId])).toEqual([{ count: 1 }]); expect(b.fixture.counts.submit - counts.submit).toBe(1); expect((await readQuote(api, b, q.itemId, q.quote.id)).consumedJobId).toBe(acceptedId); expect(state.external + state.pageErrors + fresh.state.external + fresh.state.pageErrors).toBe(0); await narrow(fresh.page);
  saveEvidence("browser-accepted-loss", { itemId: q.itemId, quoteId: q.quote.id, acceptedId, posts: state.jobPosts.length, jobRows: 1, fakePaidSubmits: b.fixture.counts.submit - counts.submit, freshContextHadNoHint: true, quoteRead404KeptBlocked: true });
});

test("QA PC3-008/009 unreceived submit and read failure preserve identity and authorization for explicit retry", async ({ browser }) => {
  const q = await seedQuote(api, b, "PC03B unconsumed response loss"); const { page, state } = await open(browser, confirmPath(q)); await consent(page); await page.locator("#budget-tripo").fill("37"); await page.locator("#budget-manual").fill("0.8"); let denyQuote = false, first = true;
  await page.route(`**/api/v1/items/${q.itemId}/estimates/${q.quote.id}`, async route => { if (!denyQuote) { await route.fallback(); return; } const r = await route.fetch({ url: `${b.base}/api/v1/items/${q.itemId}/estimates/00000000-0000-4000-8000-000000000099` }); expect(r.status()).toBe(404); await route.fulfill({ response: r }); });
  await page.route(`**/api/v1/items/${q.itemId}/jobs`, async route => { if (first) { first = false; denyQuote = true; await route.abort("failed"); } else await route.fallback(); });
  await generate(page).click(); await expect(page.getByTestId("submission-recovery")).toBeVisible(); expect(b.db("SELECT count(*) AS count FROM jobs WHERE item_id=?", [q.itemId])).toEqual([{ count: 0 }]); await expect(generate(page)).toBeDisabled();
  denyQuote = false; await page.getByRole("button", { name: "重新核对结果", exact: true }).click(); const retry = page.getByRole("button", { name: "重试同一提交（使用原授权）", exact: true }); await expect(retry).toBeVisible(); expect(state.jobPosts).toHaveLength(1); expect(Number(await page.locator("#budget-tripo").inputValue())).toBe(37); expect(Number(await page.locator("#budget-manual").inputValue())).toBe(0.8); await expect(page.locator("#budget-tripo")).toBeDisabled(); await expect(page.locator("#budget-manual")).toBeDisabled(); await expect(generate(page)).toBeDisabled(); expect((await retry.boundingBox())?.height).toBeGreaterThanOrEqual(44); await retry.focus(); await page.keyboard.press("Enter");
  await expect(page.getByTestId("job-accepted")).toBeVisible(); expect(state.jobPosts).toHaveLength(2); expect(state.jobPosts[1]).toEqual(state.jobPosts[0]); const held = state.jobPosts[0]!; const csrf = await apiLogin(api, b.base, PASSWORD); const delayed = await api.post(`${b.base}/api/v1/items/${q.itemId}/jobs`, { headers: { "x-csrf-token": csrf, "idempotency-key": held.key! }, data: held.body }); expect(delayed.status()).toBe(202); expect(delayed.headers()["x-idempotent-replay"]).toBe("true"); const jobId = (await readQuote(api, b, q.itemId, q.quote.id)).consumedJobId!; await waitForJob(api, b.base, jobId, j => j.status === "succeeded", "PC03B retry same identity", 90000); expect(b.db("SELECT count(*) AS count FROM jobs WHERE item_id=?", [q.itemId])).toEqual([{ count: 1 }]); expect(state.writes.filter(v => /POST .*\/estimates$/.test(v))).toEqual([]); expect(state.external + state.pageErrors).toBe(0); await narrow(page);
  saveEvidence("browser-same-operation", { itemId: q.itemId, quoteId: q.quote.id, jobId, sameKeyAndBody: true, budgets: { tripoCreditMinor: 3700, manualAiUsdMicros: 800000 }, automaticPostsAfterRead: 0, delayedOriginalBodyReplayReturnedSameJob: true });
});

test("QA PC3-009 actual stale-input 412 and provider unknown retain facts without automatic repurchase", async ({ browser }) => {
  const q = await seedQuote(api, b, "PC03B 412 facts"); const { page, state } = await open(browser, confirmPath(q)); await consent(page); let injected = false;
  await page.locator("#budget-tripo").fill("42"); await page.locator("#budget-manual").fill("0.9");
  await page.route(`**/api/v1/items/${q.itemId}/jobs`, async route => {
    expect(injected).toBe(false); injected = true; const csrf = await apiLogin(api, b.base, PASSWORD); const item = await api.get(`${b.base}/api/v1/items/${q.itemId}`); const headers = { "x-csrf-token": csrf, "if-match": item.headers()["etag"]! };
    expect((await api.patch(`${b.base}/api/v1/items/${q.itemId}`, { headers, data: { model: "PC03B changed during submit" } })).status()).toBe(200);
    const actualSubmit = await route.fetch({ url: `${b.base}/api/v1/items/${q.itemId}/jobs` }); expect(actualSubmit.status()).toBe(422); expect((await actualSubmit.json()).error.details.reason).toBe("inputChanged");
    // Job-create has no CAS contract. Deliver an actual item-CAS 412 envelope at this failure boundary
    // solely to exercise the frontend's specified recovery branch; do not claim native job-create 412.
    const stale = await api.patch(`${b.base}/api/v1/items/${q.itemId}`, { headers, data: { model: "Not saved stale edit" } }); expect(stale.status()).toBe(412); await route.fulfill({ response: stale });
  });
  await generate(page).click(); await expect(page.getByText("报价所用资料或配置已改变，需要重新获取报价并确认发送范围。", { exact: true })).toBeVisible(); await expect(generate(page)).toBeDisabled(); expect(b.db("SELECT count(*) AS count FROM jobs WHERE item_id=?", [q.itemId])).toEqual([{ count: 0 }]); expect(state.jobPosts).toHaveLength(1); expect(Number(await page.locator("#budget-tripo").inputValue())).toBe(42); expect(Number(await page.locator("#budget-manual").inputValue())).toBe(0.9);
  await page.getByRole("button", { name: "重新获取报价", exact: true }).click(); await expect(page.getByRole("checkbox", { name: "我已阅读并确认将上述资料发送给对应供应商", exact: true })).not.toBeChecked();
  const u = await seedQuote(api, b, "PC03B remote unknown"); b.fixture.state.submitMode = "http500"; const unknown = await open(browser, confirmPath(u)); await consent(unknown.page); await generate(unknown.page).click(); await expect(unknown.page.getByTestId("job-accepted")).toBeVisible(); const jobId = (await readQuote(api, b, u.itemId, u.quote.id)).consumedJobId!; const detail = await waitForJob(api, b.base, jobId, j => j.status === "submission_unknown", "PC03B actual local remote-unknown reservation", 90000); b.fixture.state.submitMode = "success";
  const reservations = b.db("SELECT * FROM cost_ledger WHERE snapshot_id=(SELECT snapshot_id FROM jobs WHERE id=?) ORDER BY id", [jobId]); expect(detail.reservations.length).toBeGreaterThan(0); const before = { ...b.fixture.counts }; const fresh = await open(browser, `/items/${u.itemId}/import/confirm`); await expect(fresh.page.getByTestId("job-accepted")).toContainText(jobId); await fresh.page.getByRole("link", { name: "查看任务详情", exact: true }).click(); await expect(fresh.page.getByText("付费提交结果未知：需要先对账", { exact: false })).toBeVisible(); expect(fresh.state.jobPosts).toHaveLength(0); expect(b.fixture.counts.submit).toBe(before.submit); expect(b.db("SELECT * FROM cost_ledger WHERE snapshot_id=(SELECT snapshot_id FROM jobs WHERE id=?) ORDER BY id", [jobId])).toEqual(reservations); await narrow(fresh.page);
  saveEvidence("browser-412-unknown", { staleItem: q.itemId, actualInputChanged422: true, injectedErrorSource: "actual isolated item CAS 412 envelope; job POST itself returns 422", preservedAuthorization: { tripoCreditMinor: 4200, manualAiUsdMicros: 900000 }, explicitRequoteNeedsConsent: true, unknownItem: u.itemId, jobId, unknownRetainsReservations: true, noFreshSubmit: true });
});

test("QA PC3-009 real session 401 returns to saved quote; isolated config pending cannot obscure a consumed job", async ({ browser }) => {
  // A separate QA-owned store prevents pending config from affecting other scenarios or user preview.
  const isolated = new Pc03bQaBackend(); await isolated.start(); const client = await request.newContext();
  try {
    const accepted = await seedQuote(client, isolated, "PC03B pending accepted"); await confirmQuote(client, isolated, accepted.itemId, accepted.csrf, accepted.quote.id); const jobId = await submitQuote(client, isolated, accepted); await waitForJob(client, isolated.base, jobId, j => j.status === "succeeded", "PC03B finish before isolated pending config", 90000);
    const q = await seedQuote(client, isolated, "PC03B saved quote after 401"); const { page, state, context } = await open(browser, confirmPath(q), 375, isolated); await expect(page.getByTestId("quote-panel")).toBeVisible();
    await context.clearCookies(); await page.reload(); await expect(page).toHaveURL(/\/login\?next=/); await page.getByLabel("密码", { exact: true }).fill(PASSWORD); await page.getByRole("button", { name: "登录", exact: true }).click(); await expect(page).toHaveURL(WEB + confirmPath(q)); await expect(page.getByTestId("quote-panel")).toBeVisible(); expect((await readQuote(client, isolated, q.itemId, q.quote.id)).confirmedAt ?? null).toBeNull(); expect(state.jobPosts).toHaveLength(0);
    const csrf = await apiLogin(client, isolated.base, PASSWORD); const current = await client.get(isolated.base + "/api/v1/settings/providers"); expect(current.status()).toBe(200); const config = (await current.json()).data; const unchanged = (name: "tripo" | "manualAi") => ({ action: "update", baseUrl: config.saved[name].baseUrl, model: config.saved[name].model, keyAction: "keep" });
    const pending = await client.put(isolated.base + "/api/v1/settings/providers", { headers: { "x-csrf-token": csrf }, data: { revision: config.revision, tripo: unchanged("tripo"), manualAi: { ...unchanged("manualAi"), model: "qa-local-pending-model" } } }); expect(pending.status()).toBe(200); expect((await pending.json()).data.pending).toBe(true);
    const before = businessCounts(isolated); await page.reload(); await expect(page.getByText("API 配置待重启生效；新报价、确认与生成暂不可用。", { exact: true })).toBeVisible(); await expect(generate(page)).toBeDisabled(); await expect(page.getByRole("checkbox", { name: "我已阅读并确认将上述资料发送给对应供应商", exact: true })).toBeDisabled(); expect((await readQuote(client, isolated, q.itemId, q.quote.id)).inputIssue).toBe("providerUnavailable");
    const restored = await open(browser, confirmPath(accepted), 375, isolated); await expect(restored.page.getByTestId("job-accepted")).toContainText(jobId); expect(restored.state.writes).toEqual([]); expect((await readQuote(client, isolated, accepted.itemId, accepted.quote.id)).inputIssue ?? null).toBeNull(); expect(businessCounts(isolated)).toEqual(before); await narrow(restored.page);
    saveEvidence("browser-auth-pending", { itemId: q.itemId, quoteId: q.quote.id, actualExpiredSession: true, returnToOriginalRoute: true, explicitConfirmationStillRequired: true, isolatedPendingConfig: true, acceptedItem: accepted.itemId, jobId, consumedWinsPending: true, noAdditionalBusiness: true });
  } finally { await client.dispose(); await isolated.cleanup(); }
});
