import { randomUUID } from "node:crypto";
import { expect, type APIRequestContext } from "@playwright/test";
import type { components } from "../../src/api/generated";
import { Pc05cBackend } from "./qa-pc05c-backend";
export type Stage = components["schemas"]["JobStageDto"] & { safeRetry: { number: number; limit: number } | null };
export type Detail = Omit<components["schemas"]["JobDetailDto"], "stages"> & { stages: Stage[] };
export async function detail(api: APIRequestContext, b: Pc05cBackend, id: string): Promise<Detail> { const r = await api.get(`${b.base}/api/v1/jobs/${id}`); expect(r.status()).toBe(200); return (await r.json()).data; }
/** Metadata for COUNT only, not a claim that thirty UI jobs were generated by a supplier. */
export function cloneActivityJobs(b: Pc05cBackend, source: string) {
  const active: string[] = [], inactive: string[] = [];
  for (const status of ["queued", "running", "retry_wait", "waiting_provider", "needs_input", "submission_unknown", "succeeded", "failed", "cancelled"]) {
    const group = ["queued", "running", "retry_wait", "waiting_provider"].includes(status) ? active : inactive;
    const count = group === active ? 7 : 2;
    for (let i = 0; i < count; i++) { const id = randomUUID(); b.db("INSERT INTO jobs (id,item_id,snapshot_id,status,revision,created_at,updated_at) SELECT ?,item_id,snapshot_id,?,1,?,? FROM jobs WHERE id=?", [id, status, Date.now(), Date.now(), source]); group.push(id); }
  }
  return { active, inactive };
}
