/** Independent PC02B scenarios. Authoring only until root supplies the frozen pc02b-rd-ready snapshot. */
import fs from "node:fs";
import path from "node:path";
import type {} from "../../src/features/viewer/bridge";
import { expect, request, test, type APIRequestContext, type Browser, type BrowserContext, type Locator, type Page } from "@playwright/test";
import { loginViaUi } from "./helpers";
import { Pc02bQaBackend, PASSWORD, WEB, OUT, attach, saveEvidence } from "./qa-pc02b-backend";
import { businessCounts, entities, installStale, makePublishable, patch, publish, readDraft, releaseCount, seedDraft, type DraftRef, type DraftView } from "./qa-pc02b-fixture";

test.describe.configure({ mode: "default", timeout: 120000 });
let backend: Pc02bQaBackend, api: APIRequestContext;
const contexts: BrowserContext[] = [];
test.beforeAll(async () => { backend = new Pc02bQaBackend(); await backend.start(); api = await request.newContext(); fs.mkdirSync(OUT, { recursive: true }); });
test.afterEach(async () => { for (const c of contexts.splice(0)) await c.close(); });
test.afterAll(async () => { await api?.dispose(); await backend?.cleanup(); });
const reviewUrl = (ref: DraftRef) => `${WEB}/items/${ref.itemId}/drafts/${ref.draftId}/review`;
const id = (page: Page, value: string) => page.locator(`[id=${JSON.stringify(value)}]`);
const task = (page: Page, key: string) => page.getByTestId(`todo-${key}`);
async function tabTo(page: Page, locator: Locator) { for (let n = 0; n < 180; n++) { if (await locator.evaluate(e => e === document.activeElement)) return; await page.keyboard.press("Tab"); } throw new Error("PC02B target not reachable using Tab"); }
async function enter(page: Page, locator: Locator) { await tabTo(page, locator); await page.keyboard.press("Enter"); }
async function open(browser: Browser, ref: DraftRef, width = 1440) { if (process.env.EM_PC05B_QA_WEB_ROOT) expect(browser.version()).toMatch(/^154\./); const context = await browser.newContext({ viewport: { width, height: 1000 } }); contexts.push(context); const page = await context.newPage(); page.setDefaultTimeout(15000); const state = await attach(page, backend); await loginViaUi(page, WEB, PASSWORD); state.writes.length = 0; await page.goto(reviewUrl(ref)); await expect(page.getByTestId("review-tasks")).toBeVisible(); return { page, state }; }
async function go(page: Page, key: string, focusId: string) { const button = task(page, key).getByRole("button", { name: /^去处理/ }); await expect(button).toHaveAccessibleName(/去处理 · .+ · .+/); expect((await button.boundingBox())?.height).toBeGreaterThanOrEqual(44); await enter(page, button); await expect(id(page, focusId)).toBeFocused(); }
async function back(page: Page) { await enter(page, page.getByRole("region", { name: "当前待办", exact: true }).getByRole("button", { name: "返回发布区", exact: true })); await expect(id(page, "publish-heading")).toBeFocused(); }
async function viewer(page: Page) { await expect(page.getByTestId("viewer-canvas")).toBeVisible(); await expect.poll(() => page.evaluate(() => window.__EM_VIEWER__?.stats().modelsAlive ?? 0)).toBe(1); }
function names(view: DraftView) { return { parts: view.knowledge.knowledge.parts, steps: view.knowledge.knowledge.steps, specs: view.knowledge.knowledge.specs }; }
async function noBusiness(ref: DraftRef, baseline: ReturnType<typeof businessCounts>) { expect(businessCounts(backend)).toEqual(baseline); expect(releaseCount(backend, ref)).toBe(0); }

test("QA PC2-005/008 task navigation across 375/1024/1440 preserves focus, sources and narrow geometry is read-only", async ({ browser }) => {
  const { ref, initial, csrf, baseline } = await seedDraft(api, backend, "PC02B destinations"); const { parts, steps, specs } = names(initial); const completed: number[] = [];
  for (const width of [375, 1024, 1440]) {
    const { page, state } = await open(browser, ref, width); await viewer(page); const before = (await readDraft(api, backend, ref)).dto;
    await expect(page.getByRole("checkbox", { name: "只看未完成", exact: true })).toBeChecked(); await expect(id(page, "review-group-facts")).toContainText(`未完成 ${parts.length + steps.length + specs.length}`); await expect(id(page, "review-group-model")).toContainText("未完成 2"); await expect(id(page, "review-group-geometry")).toContainText(`未完成 ${parts.length + steps.length}`);
    for (const e of entities(initial)) { await go(page, `fact-${e.id}`, `review-fact-${e.id}`); await expect(page.getByRole("region", { name: "当前待办", exact: true })).toContainText(e.name ?? e.title ?? e.label ?? ""); expect(await page.getByRole("dialog").count()).toBe(width === 375 ? 1 : 0); await back(page); }
    await go(page, "modelLoaded", "review-modelLoaded"); await back(page);
    // The second model declaration remains disabled until the first is actually saved.
    const confirmedTask = task(page, "modelConfirmed").getByRole("button"); await enter(page, confirmedTask); await expect(id(page, "review-modelConfirmed")).toBeDisabled(); await expect(page.getByRole("region", { name: "当前待办", exact: true })).toContainText("核对模型与资料一致"); await back(page);
    const part = parts[0]!; await go(page, `binding-${part.id}`, width === 375 ? `geometry-note-${part.id}` : `bind-${part.id}`); await expect(page.getByTestId("pick-mode-toggle")).toHaveAttribute("aria-pressed", "false");
    if (width === 375) { await expect(id(page, `bind-${part.id}`)).toBeDisabled(); await expect(id(page, `geometry-note-${part.id}`)).toContainText("≥768px"); }
    const source = page.getByTestId(`part-row-${part.id}`).getByRole("button", { name: /^查看出处/ }).first(); await enter(page, source); await expect(page.getByTestId("original-canvas")).toBeVisible(); expect(await page.getByRole("dialog").count()).toBe(width === 375 ? 1 : 0); await enter(page, page.getByRole("button", { name: "返回出处", exact: true })); await expect(source).toBeFocused(); await back(page);
    const step = steps[0]!; await go(page, `pose-${step.id}`, width === 375 ? `geometry-note-${step.id}` : `pose-${step.id}`); if (width === 375) await expect(id(page, `pose-${step.id}`)).toBeDisabled(); await back(page);
    await go(page, `fact-${step.id}`, `review-fact-${step.id}`); for (const resized of [375, 1024, 1440]) { await page.setViewportSize({ width: resized, height: 1000 }); await expect(page.getByRole("region", { name: "当前待办", exact: true })).toContainText(step.title ?? ""); await expect(id(page, `review-fact-${step.id}`)).toBeVisible(); expect(await page.getByRole("dialog").count()).toBeLessThanOrEqual(1); }
    expect(state.writes).toEqual([]); expect(state.external + state.pageErrors).toBe(0); expect((await readDraft(api, backend, ref)).dto).toEqual(before); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); completed.push(width);
  }
  const history = await installStale(api, backend, ref, csrf); const { page, state } = await open(browser, ref, 375); const before = (await readDraft(api, backend, ref)).dto; await go(page, `binding-${history.partId}`, `geometry-note-${history.hotspotId}`); await expect(page.getByTestId("stale-hotspots")).toContainText("不再作为有效热点"); await expect(id(page, `rebind-${history.hotspotId}`)).toBeDisabled(); expect(state.writes).toEqual([]); expect((await readDraft(api, backend, ref)).dto).toEqual(before); await noBusiness(ref, baseline);
  await page.screenshot({ path: path.join(OUT, "stale-task-375.png"), fullPage: false }); saveEvidence("navigation-matrix", { ...ref, widths: completed, realPdfSource: true, history, noNavigationWrites: true, singleDrawer: true, resizeKeptEntity: true });
});

test("QA PC2-006 explicit next updates real counts without changing context or auto-publishing", async ({ browser }) => {
  const { ref, initial, csrf, baseline } = await seedDraft(api, backend, "PC02B next and publish"); const model = initial.knowledge.model;
  // Geometry is a declared API setup fixture; the separate mouse scenario verifies actual picking.
  expect((await patch(api, backend, ref, csrf, { hotspots: { upsert: initial.knowledge.knowledge.parts.map(p => ({ partId: p.id, status: "confirmed", anchor: { modelRevisionId: model.revisionId, modelSha256: model.sha256, positionLocal: [0.2, 0.2, 1] } })) }, stepPoses: Object.fromEntries(initial.knowledge.knowledge.steps.map(s => [s.id, { positionLocal: [3, 3, 4], targetLocal: [0, 0, 0], upLocal: [0, 1, 0], fov: 45 }])) })).status()).toBe(200);
  const { page, state } = await open(browser, ref); await viewer(page); const facts = entities(initial); const firstId = facts[0]!.id; await go(page, `fact-${firstId}`, `review-fact-${firstId}`); const rows: unknown[] = [];
  // A different real client completes the selected target; explicit re-read must not choose another entity.
  expect((await patch(api, backend, ref, csrf, { entities: { [firstId]: { reviewStatus: "confirmed" } } })).status()).toBe(200); await enter(page, page.getByTestId("refresh-draft")); await expect(page.getByText("此项已变化，请重新读取待办。", { exact: true })).toBeVisible(); await expect(page.getByRole("region", { name: "当前待办", exact: true })).toContainText(facts[0]!.name ?? ""); await expect(page.getByRole("button", { name: "下一项", exact: true })).toHaveCount(0);
  expect((await patch(api, backend, ref, csrf, { entities: { [firstId]: { reviewStatus: "needs_review" } } })).status()).toBe(200); await enter(page, page.getByTestId("refresh-draft")); await expect(id(page, `review-fact-${firstId}`)).toBeEnabled(); await tabTo(page, id(page, `review-fact-${firstId}`));
  for (let index = 0; index < facts.length; index++) {
    const e = facts[index]!; const before = await readDraft(api, backend, ref); await expect(id(page, `review-fact-${e.id}`)).toBeFocused(); await page.keyboard.press("Enter"); await expect(page.getByText("此项已处理", { exact: true })).toBeVisible(); const after = await readDraft(api, backend, ref); expect(after.review.entities[e.id]?.reviewStatus).toBe("confirmed"); expect(after.dto.revision).toBe(before.dto.revision + 1); expect(after.knowledge).toEqual(before.knowledge); expect(after.review.modelReview ?? null).toEqual(before.review.modelReview ?? null);
    for (const other of facts.filter(x => x.id !== e.id)) expect(after.review.entities[other.id]).toEqual(before.review.entities[other.id]);
    await expect(id(page, "review-group-facts")).toContainText(`未完成 ${facts.length - index - 1}`); await expect(task(page, `fact-${e.id}`)).toHaveCount(0); await expect(page.getByRole("region", { name: "当前待办", exact: true })).toContainText(e.name ?? e.title ?? e.label ?? "");
    const filter = page.getByRole("checkbox", { name: "只看未完成", exact: true }); await tabTo(page, filter); await page.keyboard.press("Space"); await expect(task(page, `fact-${e.id}`)).toContainText("已确认事实"); await page.keyboard.press("Space"); await expect(page.getByRole("region", { name: "当前待办", exact: true })).toContainText("此项已处理"); expect(releaseCount(backend, ref)).toBe(0);
    rows.push({ id: e.id, revision: after.dto.revision }); await enter(page, page.getByRole("button", { name: "下一项", exact: true }));
  }
  await expect(id(page, "review-modelLoaded")).toBeFocused(); await page.keyboard.press("Enter"); await expect(page.getByText("此项已处理", { exact: true })).toBeVisible(); const loaded = await readDraft(api, backend, ref); expect(loaded.review.modelReview?.loaded).toBe(true); expect(loaded.review.modelReview?.userConfirmed).toBe(false);
  await enter(page, page.getByRole("button", { name: "下一项", exact: true })); await expect(id(page, "review-modelConfirmed")).toBeFocused(); await page.keyboard.press("Enter"); await expect(page.getByText("待办已处理，可返回发布区核对。", { exact: true })).toBeVisible(); expect(releaseCount(backend, ref)).toBe(0); await back(page);
  await page.setViewportSize({ width: 375, height: 1000 }); const button = page.getByRole("button", { name: "发布（生成不可变版本）", exact: true }); await expect(button).toBeVisible(); await expect(button).toBeEnabled(); expect((await button.boundingBox())?.height).toBeGreaterThanOrEqual(44); await enter(page, button); await expect(page.getByTestId("publish-success")).toBeVisible(); expect(releaseCount(backend, ref)).toBe(1); expect(businessCounts(backend)).toEqual(baseline); expect(state.external + state.pageErrors).toBe(0);
  saveEvidence("explicit-next", { ...ref, rows, finalModelDeclarationsIndependent: true, releaseCount: 1, explicitPublishOn375: true, noAdditionalBusiness: true });
});

test("QA PC2-007 real save/publish 412 retain dirty text; known and hostile unknown 422 remain actionable", async ({ browser }) => {
  const { ref, initial, csrf, baseline } = await seedDraft(api, backend, "PC02B conflicts and 422"); const part = initial.knowledge.knowledge.parts[0]!, spec = initial.knowledge.knowledge.specs[0]!;
  const rejection = await publish(api, backend, ref, csrf, initial.etag); expect(rejection.status()).toBe(422); const realKnownError = await rejection.json(); await makePublishable(api, backend, ref, csrf);
  const { page, state } = await open(browser, ref); const row = page.getByTestId(`knowledge-${part.id}`); await row.getByRole("button", { name: "复制为本地修订", exact: true }).click(); await row.getByLabel("部件名", { exact: true }).fill("QA local unsaved name"); saveEvidence("edit-control-diagnostic", { labels: await row.locator("label").allTextContents(), textareas: await row.locator("textarea").count(), bodyName: await row.getByLabel("部件名", { exact: true }).inputValue() }); await row.getByLabel(/^说明/).fill("QA local unsaved description");
  expect((await patch(api, backend, ref, csrf, { entities: { [spec.id]: { userEdited: { value: "remote change one" } } } })).status()).toBe(200);
  const saveResponse = page.waitForResponse(r => r.request().method() === "PATCH" && r.url().endsWith(`/drafts/${ref.draftId}`)); await row.getByRole("button", { name: "保存人工修订（并确认事实）", exact: true }).click(); expect((await saveResponse).status()).toBe(412); await expect(row.getByLabel("部件名", { exact: true })).toHaveValue("QA local unsaved name"); await expect(row.getByLabel(/^说明/)).toHaveValue("QA local unsaved description");
  let dialogs = 0; const discardDialog = page.getByRole("dialog", { name: "离开当前页面？", exact: true });
  async function discardChoice(accept: boolean) { await expect(discardDialog).toBeVisible(); await expect(page.locator("dialog[open]")).toHaveCount(1); await expect(discardDialog).toContainText("本页所有未保存的知识修订"); const cancel = discardDialog.getByRole("button", { name: "继续处理", exact: true }); await expect(cancel).toBeFocused(); dialogs++; await discardDialog.getByRole("button", { name: accept ? "丢弃本页修改并加载最新版本" : "继续处理", exact: true }).click(); await expect(discardDialog).toBeHidden(); }
  await enter(page, page.getByTestId("conflict-panel").getByRole("button", { name: "核对最新版本", exact: true })); await discardChoice(false); expect(dialogs).toBe(1); await expect(row.getByLabel("部件名", { exact: true })).toHaveValue("QA local unsaved name");
  await enter(page, page.getByTestId("conflict-panel").getByRole("button", { name: "核对最新版本", exact: true })); await discardChoice(true); await expect(row.getByLabel("部件名", { exact: true })).toHaveCount(0); expect(dialogs).toBe(2);
  await row.getByRole("button", { name: "复制为本地修订", exact: true }).click(); await row.getByLabel("部件名", { exact: true }).fill("QA publish conflict unsaved"); expect((await patch(api, backend, ref, csrf, { entities: { [spec.id]: { userEdited: { value: "remote change two" } } } })).status()).toBe(200);
  const publishButton = page.getByRole("button", { name: "发布（生成不可变版本）", exact: true }); const publishResponse = page.waitForResponse(r => r.url().endsWith(`/drafts/${ref.draftId}/publish`)); await enter(page, publishButton); expect((await publishResponse).status()).toBe(412); await expect(row.getByLabel("部件名", { exact: true })).toHaveValue("QA publish conflict unsaved"); expect(releaseCount(backend, ref)).toBe(0);
  // Fail the actual refresh GET at a real absent endpoint; dirty text and local recovery must stay available.
  await enter(page, page.getByTestId("publish-conflict").getByRole("button", { name: "核对最新版本", exact: true })); await expect(discardDialog).toBeVisible();
  const draftPattern = `**/api/v1/items/${ref.itemId}/drafts/${ref.draftId}`; await page.route(draftPattern, route => route.request().method() === "GET" ? route.continue({ url: `${backend.base}/api/v1/items/${ref.itemId}/drafts/01930000-0000-7000-8000-000000000098` }) : route.fallback());
  await discardChoice(true); await expect(page.getByText(/读取失败，本地编辑仍保留/)).toBeVisible(); await expect(row.getByLabel("部件名", { exact: true })).toHaveValue("QA publish conflict unsaved"); await page.unroute(draftPattern);
  await enter(page, page.getByTestId("publish-conflict").getByRole("button", { name: "核对最新版本", exact: true })); await discardChoice(true); await expect(row.getByLabel("部件名", { exact: true })).toHaveCount(0); await expect(publishButton).toBeEnabled();
  const publishPattern = `${draftPattern}/publish`; let errorsDelivered = 0;
  // Negative-only replay: envelope came from the real failed publish above; no successful data is mocked.
  await page.route(publishPattern, async route => { errorsDelivered++; await route.fulfill({ status: 422, contentType: "application/json", body: JSON.stringify(realKnownError) }); }); await enter(page, publishButton); const issues = page.getByTestId("publish-issues"); await expect(issues).toContainText(realKnownError.error.requestId); await expect(issues.getByRole("button", { name: new RegExp(`^去处理 · ${part.name} ·`) }).first()).toBeVisible(); await enter(page, issues.getByRole("button", { name: new RegExp(`^去处理 · ${part.name} ·`) }).first()); await expect(page.getByRole("region", { name: "当前待办", exact: true })).toContainText(part.name ?? ""); await back(page); await page.unroute(publishPattern); await enter(page, issues.getByRole("button", { name: "重新读取检查结果", exact: true })); await expect(issues).toContainText(realKnownError.error.requestId); const retryPublish = page.getByRole("button", { name: "重新检查并发布（通过后生成不可变版本）", exact: true }); await expect(retryPublish).toBeEnabled();
  const hostile = '<img src="https://qa-invalid.example.invalid/no-call" onerror="document.body.dataset.pc02bInjected=1">'; const unknown = { error: { code: "validation_failed", message: "QA unknown publish requirements", requestId: "QA-PC02B-UNKNOWN", details: { issues: [{ code: "futureUnknownCode", message: hostile, entityId: hostile, entityKind: "part" }, { code: "knowledgeUnreviewed", message: "QA missing target", entityId: null, entityKind: "part" }] } } };
  await page.route(publishPattern, async route => { errorsDelivered++; await route.fulfill({ status: 422, contentType: "application/json", body: JSON.stringify(unknown) }); }); await enter(page, retryPublish); await expect(issues).toContainText("futureUnknownCode"); await expect(issues).toContainText("QA-PC02B-UNKNOWN"); await expect(issues.getByRole("button", { name: /^去处理/ })).toHaveCount(0); await expect(publishButton).toBeDisabled(); expect(await page.evaluate(() => document.body.dataset.pc02bInjected ?? null)).toBeNull(); await expect(page.locator('img[src*="qa-invalid"]')).toHaveCount(0); expect(state.external).toBe(0); await page.unroute(publishPattern); await enter(page, issues.getByRole("button", { name: "重新读取检查结果", exact: true })); await expect(issues).toContainText("QA-PC02B-UNKNOWN"); await expect(issues).toContainText("尚未确认解决"); await expect(retryPublish).toBeEnabled(); await noBusiness(ref, baseline); const finalPublish = page.waitForResponse(r => r.url().endsWith(`/drafts/${ref.draftId}/publish`)); await enter(page, retryPublish); expect((await finalPublish).status()).toBe(201); await expect(issues).toHaveCount(0); expect(releaseCount(backend, ref)).toBe(1); expect(businessCounts(backend)).toEqual(baseline);
  saveEvidence("conflicts-and-issues", { ...ref, actualStatuses: { save: 412, publish: 412, originalKnownPublish: 422 }, negativeErrorReplays: errorsDelivered, unknownIssuesHaveNoTarget: true, noInjectedDomOrExternalRequest: true, canceledRefreshKeptText: true, failedRefreshKeptText: true, explicitRefreshReplacedText: true, unknownDiagnosticsSurvivedGet: true, explicitRecheckPublishedOneRelease: true });
});

test("QA PC2-008 rotation, explicit binding and cancellation preserve real anchors and independent step poses", async ({ browser }) => {
  const { ref, initial, csrf, baseline } = await seedDraft(api, backend, "PC02B geometry regression"); const part = initial.knowledge.knowledge.parts[0]!, step = initial.knowledge.knowledge.steps[0]!; const { page, state } = await open(browser, ref); await viewer(page); await go(page, `binding-${part.id}`, `bind-${part.id}`); const canvas = page.getByTestId("viewer-canvas"); const box = await canvas.boundingBox(); if (!box) throw new Error("Missing actual WebGL viewport");
  const drag = async () => { await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2); await page.mouse.down(); await page.mouse.move(box.x + box.width / 2 + 70, box.y + box.height / 2 + 35, { steps: 12 }); await page.mouse.up(); };
  const clickModel = async () => { const projected = await page.evaluate(() => window.__EM_VIEWER__?.project([0, 0, 0]) ?? null); if (!projected) throw new Error("No actual model projection"); await canvas.click({ position: { x: projected.screen[0], y: projected.screen[1] } }); };
  const before = await readDraft(api, backend, ref); await drag(); await clickModel(); expect((await readDraft(api, backend, ref)).dto).toEqual(before.dto); expect(state.writes).toEqual([]);
  await enter(page, id(page, `bind-${part.id}`)); await expect(page.getByTestId("pick-mode-toggle")).toHaveAttribute("aria-pressed", "true"); await expect(page.getByRole("group", { name: "热点校准模式" })).toContainText(`当前绑定部件：${part.name}`); await drag(); expect((await readDraft(api, backend, ref)).knowledge.hotspots).toEqual(before.knowledge.hotspots); await enter(page, page.getByRole("button", { name: "取消拾取", exact: true })); await clickModel(); expect((await readDraft(api, backend, ref)).dto).toEqual(before.dto);
  await enter(page, id(page, `bind-${part.id}`)); const saved = page.waitForResponse(r => r.request().method() === "PATCH" && r.url().endsWith(`/drafts/${ref.draftId}`)); await clickModel(); expect((await saved).status()).toBe(200); await expect(page.getByTestId(`part-hotspot-${part.id}`)).toContainText("热点已确认 1"); const bound = await readDraft(api, backend, ref); const hotspot = bound.knowledge.hotspots.find(h => h.partId === part.id)!; expect(hotspot.status).toBe("confirmed"); expect(hotspot.anchor?.modelSha256).toBe(initial.knowledge.model.sha256); expect(hotspot.anchor?.modelRevisionId).toBe(initial.knowledge.model.revisionId); expect(hotspot.anchor?.positionLocal.every(Number.isFinite)).toBe(true); expect(bound.review).toEqual(before.review);
  await back(page); await go(page, `pose-${step.id}`, `pose-${step.id}`); await page.keyboard.press("Enter"); await expect(page.getByTestId(`step-pose-${step.id}`)).toHaveText("视角已保存"); const posed = await readDraft(api, backend, ref); expect(posed.knowledge.hotspots).toEqual(bound.knowledge.hotspots); expect(posed.knowledge.stepPoses?.[step.id]).toBeDefined(); await page.getByTestId(`step-row-${step.id}`).getByRole("button", { name: "清除视角", exact: true }).click(); await expect.poll(async () => (await readDraft(api, backend, ref)).knowledge.stepPoses?.[step.id]).toBeUndefined(); expect((await readDraft(api, backend, ref)).knowledge.hotspots).toEqual(bound.knowledge.hotspots);
  const history = await installStale(api, backend, ref, csrf); await page.reload(); await viewer(page); await go(page, `binding-${part.id}`, `rebind-${history.hotspotId}`); await expect(page.getByTestId(`part-hotspot-${part.id}`)).toContainText("未绑定"); await expect(page.getByTestId("stale-hotspots")).toContainText("不再作为有效热点"); await page.keyboard.press("Enter"); const reboundResponse = page.waitForResponse(r => r.request().method() === "PATCH" && r.url().endsWith(`/drafts/${ref.draftId}`)); await clickModel(); expect((await reboundResponse).status()).toBe(200); const rebound = await readDraft(api, backend, ref); expect(rebound.knowledge.hotspots.find(h => h.id === history.hotspotId)?.anchor?.modelSha256).toBe(initial.knowledge.model.sha256); await noBusiness(ref, baseline); expect(state.external + state.pageErrors).toBe(0);
  saveEvidence("geometry-regression", { ...ref, actualWebGlPicking: true, dragAndCanceledPickWroteNothing: true, confirmedHotspotId: hotspot.id, positionLocal: hotspot.anchor?.positionLocal, history, rebindUsesCurrentModel: true, posesDidNotChangeHotspots: true });
});
