/** Actual PDF.js output and persisted HTTP facts. No seedReadyPreparation or successful metadata mocks. */
import fs from "node:fs";
import path from "node:path";
import { expect, request, test, type APIRequestContext, type Browser, type BrowserContext, type Locator, type Page } from "@playwright/test";
import type { components } from "../../src/api/generated";
import { apiLogin, fetchAsset, loginViaUi } from "./helpers";
import { fixturePath } from "./runtime";
import { Pc03aQaBackend, PASSWORD, WEB, OUT, attach, digest, saveEvidence } from "./qa-pc03a-backend";
type Doc = components["schemas"]["DocumentDto"];
type Detail = components["schemas"]["PreparationDetailDto"];
type PagePut = components["schemas"]["PagePutRequest"];
test.describe.configure({ mode: "serial", timeout: 120000 });
let backend: Pc03aQaBackend, api: APIRequestContext, csrf: string;
const contexts: BrowserContext[] = [];
test.beforeAll(async () => { backend = new Pc03aQaBackend(); await backend.start(); api = await request.newContext(); csrf = await apiLogin(api, backend.base, PASSWORD); fs.mkdirSync(OUT, { recursive: true }); });
test.afterEach(async () => { for (const c of contexts.splice(0)) await c.close(); expect(backend.fixture.counts).toEqual({ upload: 0, submit: 0, task: 0, manual: 0, cdn: 0 }); expect(backend.db("SELECT (SELECT count(*) FROM jobs) AS jobs,(SELECT count(*) FROM provider_attempts) AS attempts,(SELECT count(*) FROM cost_ledger) AS ledger,(SELECT count(*) FROM quotes) AS quotes")).toEqual([{ jobs: 0, attempts: 0, ledger: 0, quotes: 0 }]); });
test.afterAll(async () => { await api?.dispose(); await backend?.cleanup(); });
async function newDocument(itemId?: string, fixture = "sample-manual-text.pdf") {
  if (!itemId) { const item = await api.post(backend.base + "/api/v1/items", { headers: { "x-csrf-token": csrf }, data: { name: "PC03A real PDF.js independent QA", model: "Synthetic manual" } }); expect(item.status()).toBe(201); itemId = (await item.json()).data.id as string; }
  const bytes = fs.readFileSync(fixturePath(fixture)); const uploaded = await api.post(`${backend.base}/api/v1/items/${itemId}/assets`, { headers: { "x-csrf-token": csrf }, multipart: { purpose: "document", file: { name: fixture, mimeType: "application/pdf", buffer: bytes } } }); expect(uploaded.status()).toBe(201); const asset = (await uploaded.json()).data;
  const bound = await api.post(`${backend.base}/api/v1/items/${itemId}/documents`, { headers: { "x-csrf-token": csrf }, data: { sourceAssetId: asset.id, title: `QA ${fixture}` } }); expect(bound.status()).toBe(201); const doc = (await bound.json()).data as Doc; expect(doc.sourceSha256).toBe(digest(bytes)); return { itemId, doc };
}
function url(itemId: string, doc: Doc, step = "prepare") { return `${WEB}/items/${itemId}/import/${step}?documentId=${doc.id}`; }
async function boot(browser: Browser, width = 1440) { const context = await browser.newContext({ viewport: { width, height: 900 } }); contexts.push(context); const page = await context.newPage(); const state = await attach(page, backend); await loginViaUi(page, WEB, PASSWORD); state.writes.length = 0; state.pagePuts.length = 0; state.assetReads = 0; return { context, page, state }; }
async function tabTo(page: Page, target: Locator) { for (let i = 0; i < 150; i++) { await page.keyboard.press("Tab"); if (await target.evaluate(el => el === document.activeElement)) return; } throw new Error("PC03A control is not reachable by Tab"); }
async function enter(page: Page, target: Locator) { await tabTo(page, target); await page.keyboard.press("Enter"); }
async function resource(id: string) { const r = await api.get(`${backend.base}/api/v1/preparations/${id}`); expect(r.status()).toBe(200); const etag = r.headers()["etag"]; if (!etag) throw new Error("Missing preparation ETag"); return { data: (await r.json()).data as Detail, etag }; }
function prepFacts(id: string) { return { record: backend.db("SELECT * FROM preparations WHERE id=?", [id]), pages: backend.db("SELECT * FROM pages WHERE preparation_id=? ORDER BY page_number", [id]) }; }
async function currentId(page: Page) { const id = await page.getByRole("region", { name: "当前准备进度" }).locator("code").textContent(); if (!id) throw new Error("Missing current preparation ID"); return id; }
async function seal(page: Page) { await expect(page.getByTestId("prepare-seal")).toBeEnabled(); await enter(page, page.getByTestId("prepare-seal")); await expect(page.getByTestId("prepare-sealed")).toBeVisible(); }
async function verifyPage(id: string, number: number) {
  const row = (await resource(id)).data.pages.find(p => p.pageNumber === number); if (!row?.imageAssetId || !row.textAssetId || !row.viewport) throw new Error("Real PDF.js page assets missing");
  const image = await fetchAsset(api, backend.base, row.imageAssetId); const text = await fetchAsset(api, backend.base, row.textAssetId); expect(image.contentType).toContain("image/jpeg"); expect([...image.bytes.subarray(0, 3)]).toEqual([255, 216, 255]); expect(Math.max(row.viewport.width, row.viewport.height)).toBeLessThanOrEqual(2000); expect(text.bytes.toString()).toContain(`Page ${number} of 2`);
  const imageSha = digest(image.bytes), textSha = digest(text.bytes); expect(backend.db("SELECT id,blob_id FROM assets WHERE id IN (?,?) ORDER BY id", [row.imageAssetId, row.textAssetId])).toEqual([{ id: row.imageAssetId, blob_id: imageSha }, { id: row.textAssetId, blob_id: textSha }].sort((a, b) => a.id.localeCompare(b.id)));
  return { number, imageAssetId: row.imageAssetId, textAssetId: row.textAssetId, imageSha, textSha, viewport: row.viewport };
}
async function assertReadOnly(pageState: Awaited<ReturnType<typeof attach>>, before: ReturnType<Pc03aQaBackend["snapshot"]>) { expect(pageState.writes).toEqual([]); expect(pageState.assetReads).toBe(0); expect(pageState.pagePuts).toEqual([]); expect(pageState.external + pageState.pageErrors).toBe(0); expect(backend.snapshot()).toEqual(before); }

test("QA PC3-001/002/004/005 real stop, fresh contexts, missing-only PDF.js continuation and ready reuse", async ({ browser }) => {
  const { itemId, doc } = await newDocument(); const first = await boot(browser, 375); await first.page.goto(url(itemId, doc)); await expect(first.page.getByTestId("prepare-start")).toHaveText("开始准备");
  let release: () => void = () => {}; const gate = new Promise<void>(resolve => { release = resolve; }); let held = false, id = "";
  const pattern = "**/api/v1/preparations/*/pages/1";
  await first.page.route(pattern, async route => { id = /\/preparations\/([^/]+)\/pages\/1$/.exec(new URL(route.request().url()).pathname)?.[1] ?? ""; held = true; await gate; await route.fallback(); });
  try {
    await enter(first.page, first.page.getByTestId("prepare-start")); await expect.poll(() => held).toBe(true); await expect(first.page.getByLabel("所选原件", { exact: true })).toBeDisabled(); await expect(first.page.getByText("请先停止当前准备，再切换原件。", { exact: true })).toBeVisible();
    const stop = first.page.getByTestId("prepare-cancel"); expect((await stop.boundingBox())?.height).toBeGreaterThanOrEqual(44); await enter(first.page, stop); await expect(stop).toHaveText("正在停止并读取进度…"); release(); await expect(first.page.getByText("已停止，已完成页已保留。可稍后继续准备。", { exact: true })).toBeVisible();
  } finally { release(); }
  await first.page.unroute(pattern); expect(first.state.pagePuts).toEqual([1]); const stopped = await resource(id); expect(stopped.data.state).toBe("preparing"); expect(stopped.data.pageCount).toBeNull(); expect(stopped.data.readiness.completedPages).toEqual([1]); const pageOne = await verifyPage(id, 1); const pageOneRow = backend.db("SELECT * FROM pages WHERE preparation_id=? AND page_number=1", [id]); await first.context.close();
  const partialConfirm = await boot(browser); const partialBefore = backend.snapshot(); await partialConfirm.page.goto(url(itemId, doc, "confirm")); await expect(partialConfirm.page.getByText("可继续的准备记录 · 推荐", { exact: true })).toBeVisible(); const continueLink = partialConfirm.page.getByRole("link", { name: "继续准备，仅补齐缺页", exact: true }); await expect(continueLink).toHaveAttribute("href", new RegExp(`preparationId=${id}`)); await assertReadOnly(partialConfirm.state, partialBefore); await partialConfirm.context.close();
  const fresh = await boot(browser, 375); expect(await fresh.page.evaluate(() => sessionStorage.length)).toBe(0); const before = backend.snapshot(); await fresh.page.goto(url(itemId, doc)); await expect(fresh.page.getByTestId("prepare-progress")).toHaveText("已完成 1 页，总页数待读取原件"); await expect(fresh.page.getByRole("progressbar")).toHaveCount(0); await expect(fresh.page.locator("body")).not.toContainText("0%"); await assertReadOnly(fresh.state, before);
  const resume = fresh.page.getByTestId("prepare-start"); expect((await resume.boundingBox())?.height).toBeGreaterThanOrEqual(44); await enter(fresh.page, resume); await expect(fresh.page.getByTestId("prepare-seal")).toBeEnabled(); expect(fresh.state.pagePuts).toEqual([2]); expect(fresh.state.writes.some(p => p.endsWith("/complete") || /\/documents\/[^/]+\/preparations$/.test(p))).toBe(false); expect((await resource(id)).data.state).toBe("preparing"); expect(backend.db("SELECT * FROM pages WHERE preparation_id=? AND page_number=1", [id])).toEqual(pageOneRow); const pageTwo = await verifyPage(id, 2); await expect(fresh.page.getByTestId("prepare-progress")).toHaveText("已完成 2/2 页");
  await seal(fresh.page); await expect(fresh.page.getByTestId("prepare-sealed")).toHaveText("准备完成 · 2 页"); const next = fresh.page.getByRole("link", { name: /^下一步：/ }); expect((await next.boundingBox())?.height).toBeGreaterThanOrEqual(44); await expect(next).toHaveAttribute("href", new RegExp(`preparationId=${id}`)); expect(await fresh.page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); await fresh.page.screenshot({ path: path.join(OUT, "real-prepared-375.png"), fullPage: true }); const readyFacts = prepFacts(id);
  await enter(fresh.page, next); await expect(fresh.page.getByText("可直接使用的准备结果 · 推荐", { exact: true })).toBeVisible(); await fresh.context.close();
  const confirmation = await boot(browser); const confirmedBefore = backend.snapshot(); await confirmation.page.goto(url(itemId, doc, "confirm")); await expect(confirmation.page.getByText("可直接使用的准备结果 · 推荐", { exact: true })).toBeVisible(); await expect(confirmation.page.getByText("准备完成 · 2 页", { exact: true })).toBeVisible(); await expect(confirmation.page.getByTestId("generate-button")).toBeDisabled(); await assertReadOnly(confirmation.state, confirmedBefore); expect(prepFacts(id)).toEqual(readyFacts);
  saveEvidence("browser-real-resume", { itemId, documentId: doc.id, preparationId: id, actualPdfJs: true, stoppedPuts: first.state.pagePuts, resumedPuts: fresh.state.pagePuts, savedPageOneUnchanged: true, totalBeforeRead: null, totalAfterRead: 2, explicitSeal: true, pages: [pageOne, pageTwo], freshPreparationAndConfirmationReadOnly: true, generatedStateDelta: 0 });
});

test("QA PC3-004 actual stale complete 412 recovers by re-reading a remotely sealed record", async ({ browser }) => {
  const { itemId, doc } = await newDocument(); const session = await boot(browser); await session.page.goto(url(itemId, doc)); await session.page.getByTestId("prepare-start").click(); await expect(session.page.getByTestId("prepare-seal")).toBeEnabled(); const id = await currentId(session.page); const pages = [await verifyPage(id, 1), await verifyPage(id, 2)]; let once = true, staleStatus = 0;
  session.page.on("response", response => { if (response.url().endsWith(`/preparations/${id}/complete`)) staleStatus = response.status(); });
  await session.page.route(`**/api/v1/preparations/${id}/complete`, async route => {
    if (once) { once = false; const old = await resource(id); const first = old.data.pages[0]; if (!first?.viewport) throw new Error("Missing real first page"); const body: PagePut = { imageAssetId: first.imageAssetId, textAssetId: first.textAssetId, viewport: { ...first.viewport, rotation: 90 } }; const changed = await api.put(`${backend.base}/api/v1/preparations/${id}/pages/1`, { headers: { "x-csrf-token": csrf, "if-match": old.etag }, data: body }); expect(changed.status()).toBe(200); }
    await route.fallback();
  });
  await session.page.getByTestId("prepare-seal").click(); await expect(session.page.getByRole("alert")).toContainText("记录已更新，请重新读取进度"); expect(staleStatus).toBe(412); await expect(session.page.getByTestId("prepare-start")).toBeDisabled();
  // A second real client seals successfully while the first tab is paused at conflict.
  const current = await resource(id); const sealed = await api.post(`${backend.base}/api/v1/preparations/${id}/complete`, { headers: { "x-csrf-token": csrf, "if-match": current.etag }, data: { pageCount: 2 } }); expect(sealed.status()).toBe(200); const ready = prepFacts(id); session.state.writes.length = 0; session.state.assetReads = 0; session.state.pagePuts.length = 0; const before = backend.snapshot();
  await enter(session.page, session.page.getByRole("button", { name: "重新读取进度", exact: true })); await expect(session.page.getByTestId("prepare-sealed")).toHaveText("准备完成 · 2 页"); await expect(session.page.getByTestId("prepare-start")).toBeHidden(); await expect(session.page.getByTestId("prepare-seal")).toBeHidden(); await assertReadOnly(session.state, before); expect(prepFacts(id)).toEqual(ready);
  saveEvidence("browser-real-conflict", { itemId, documentId: doc.id, preparationId: id, initialActualPdfJsPages: pages, fault: "second client changed page viewport before first complete request; true server CAS", completeStatus: staleStatus, secondClientSeal: 200, recoveryReadOnly: true, readyUnchanged: true });
});

test("QA PC3-001/003/005 mobile radios, read failure, poisoned cache and delayed old document discovery", async ({ browser }) => {
  const { itemId, doc: first } = await newDocument(); const { doc: second } = await newDocument(itemId, "sample-manual-nonlatin.pdf"); const session = await boot(browser, 375); await session.page.goto(url(itemId, first)); await session.page.getByTestId("prepare-start").click(); await expect(session.page.getByTestId("prepare-seal")).toBeEnabled(); const firstId = await currentId(session.page); await verifyPage(firstId, 1); await verifyPage(firstId, 2); await seal(session.page);
  // Cached ready from first document must not complete the second document.
  const fresh = await boot(browser, 375); await fresh.page.evaluate(({ itemId, firstId }) => sessionStorage.setItem(`em.prepare.${itemId}`, firstId), { itemId, firstId }); const before = backend.snapshot(); await fresh.page.goto(url(itemId, second)); await expect(fresh.page.getByText("之前的记录不适用于当前原件；以下以服务端读取结果为准。", { exact: true })).toBeVisible(); await expect(fresh.page.getByText("当前原件尚无准备记录。点击开始后才会读取并制作页资料。", { exact: true })).toBeVisible(); await expect(fresh.page.getByTestId("prepare-sealed")).toBeHidden(); await assertReadOnly(fresh.state, before);
  await enter(fresh.page, fresh.page.getByTestId("prepare-start")); await expect(fresh.page.getByTestId("prepare-seal")).toBeEnabled(); const secondId = await currentId(fresh.page); expect(secondId).not.toBe(firstId); expect((await resource(secondId)).data.documentId).toBe(second.id); await seal(fresh.page); const readySecond = prepFacts(secondId);
  // Synthetic empty v1 history only tests list discovery/radios; actual ready pages above came from PDF.js.
  const padding = Array.from({ length: 21 }, (_, i) => [`qa-ui-empty-${i}`, second.id, second.sourceSha256, 2000000000000 + i, 2000000000000 + i]); backend.db(`INSERT INTO preparations(id,document_id,source_sha256,state,page_count,client_derived,revision,created_at,updated_at,format_version) VALUES ${padding.map(() => "(?,?,?,'preparing',NULL,0,1,?,?,1)").join(",")}`, padding.flat());
  await fresh.page.reload(); await expect(fresh.page.getByTestId("prepare-sealed")).toHaveText("准备完成 · 1 页"); await enter(fresh.page, fresh.page.locator(".preparation-discovery summary")); const load = fresh.page.getByRole("button", { name: "加载更多准备记录", exact: true }); expect((await load.boundingBox())?.height).toBeGreaterThanOrEqual(44); await enter(fresh.page, load); await expect(fresh.page.locator(".preparation-discovery summary")).toContainText("22 条");
  const radio = fresh.page.locator(`input[type=radio][value="${secondId}"]`); await tabTo(fresh.page, radio); const originalRadioNode = await radio.elementHandle();
  let detailRequested = false, releaseDetail: () => void = () => {}; const detailGate = new Promise<void>(resolve => { releaseDetail = resolve; }); const detailPattern = "**/api/v1/preparations/qa-ui-empty-20";
  await fresh.page.route(detailPattern, async route => { detailRequested = true; await detailGate; await route.fallback(); });
  try {
    await fresh.page.keyboard.press("ArrowDown"); await expect.poll(() => detailRequested).toBe(true);
    await expect(fresh.page.locator('input[name="preparation-record"]:checked')).toBeFocused(); expect(await originalRadioNode?.evaluate(node => node.isConnected)).toBe(true); await expect(fresh.page.locator(".preparation-discovery details")).toHaveAttribute("open", "");
    await expect(fresh.page.getByTestId("prepare-start")).toBeHidden(); await expect(fresh.page.getByTestId("prepare-seal")).toBeHidden(); await expect(fresh.page.getByRole("link", { name: /^下一步：/ })).toHaveCount(0);
    saveEvidence("browser-radio-pending", { selectedRadioFocused: true, originalRadioNodeConnected: true, otherRecordsExpanded: true, startSealAndNextUnavailable: true });
  } finally { releaseDetail(); }
  await expect(fresh.page.getByTestId("prepare-progress")).toHaveText("已完成 0 页，总页数待读取原件"); await fresh.page.unroute(detailPattern);
  const focusAfterSelection = await fresh.page.evaluate(() => ({ activeTag: document.activeElement?.tagName, activeId: document.activeElement?.id, activeValue: (document.activeElement as HTMLInputElement | null)?.value, checkedValue: (document.querySelector('input[name="preparation-record"]:checked') as HTMLInputElement | null)?.value, otherRecordsExpanded: document.querySelector(".preparation-discovery details")?.hasAttribute("open") })); saveEvidence("browser-radio-focus", { ...focusAfterSelection, originalRadioNodeConnected: await originalRadioNode?.evaluate(node => node.isConnected) }); await expect(fresh.page.locator('input[name="preparation-record"]:checked')).toBeFocused();
  await fresh.page.keyboard.press("ArrowUp"); await expect(fresh.page.getByTestId("prepare-sealed")).toHaveText("准备完成 · 1 页"); expect(await fresh.page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); await fresh.page.screenshot({ path: path.join(OUT, "discovery-records-375.png"), fullPage: true });
  // Unknown cached ID is a non-authoritative hint. Actual selected ready stays server-derived.
  await fresh.page.evaluate(itemId => sessionStorage.setItem(`em.prepare.${itemId}`, "01930000-0000-7000-8000-000000000094"), itemId); await fresh.page.reload(); await expect(fresh.page.getByText("之前的记录不适用于当前原件；以下以服务端读取结果为准。", { exact: true })).toBeVisible(); await expect(fresh.page.getByTestId("prepare-sealed")).toHaveText("准备完成 · 1 页");
  // Explicit wrong requested ID is blocked and offers a deliberate correct recommendation.
  await fresh.page.goto(url(itemId, second) + `&preparationId=${firstId}`); await expect(fresh.page.getByRole("heading", { name: "准备记录读取失败", exact: true })).toBeVisible(); await expect(fresh.page.getByTestId("prepare-sealed")).toBeHidden(); await expect(fresh.page.getByTestId("prepare-start")).toBeHidden(); await enter(fresh.page, fresh.page.getByRole("button", { name: "使用当前原件的推荐记录", exact: true })); await expect(fresh.page.getByTestId("prepare-sealed")).toHaveText("准备完成 · 1 页");
  const failing = `**/api/v1/documents/${second.id}/preparations?*`; await fresh.page.route(failing, route => route.continue({ url: backend.base + "/api/v1/documents/01930000-0000-7000-8000-000000000094/preparations" })); fresh.state.writes.length = 0; fresh.state.pagePuts.length = 0; fresh.state.assetReads = 0; const failureBefore = backend.snapshot();
  await fresh.page.goto(url(itemId, second)); await expect(fresh.page.getByRole("heading", { name: "准备记录读取失败", exact: true })).toBeVisible(); await expect(fresh.page.getByTestId("prepare-start")).toBeHidden(); await expect(fresh.page.getByTestId("prepare-sealed")).toBeHidden(); await expect(fresh.page.getByText("当前原件尚无准备记录。点击开始后才会读取并制作页资料。", { exact: true })).toBeHidden(); await fresh.page.unroute(failing); const retry = fresh.page.getByRole("button", { name: "重新读取", exact: true }); expect((await retry.boundingBox())?.height).toBeGreaterThanOrEqual(44); await enter(fresh.page, retry); await expect(fresh.page.getByTestId("prepare-sealed")).toHaveText("准备完成 · 1 页"); await assertReadOnly(fresh.state, failureBefore);
  // Hold an actual first-document response while switching to second; release only after second is ready.
  const late = await boot(browser, 375); let release: () => void = () => {}; let fetched = false, settled = false; const gate = new Promise<void>(resolve => { release = resolve; }); const pattern = `**/api/v1/documents/${first.id}/preparations?*`;
  await late.page.route(pattern, async route => { const u = new URL(route.request().url()); const response = await route.fetch({ url: backend.base + u.pathname + u.search }); fetched = true; await gate; try { await route.fulfill({ response }); } catch { /* canceled old discovery is expected */ } finally { settled = true; } });
  try { const delayedBefore = backend.snapshot(); await late.page.goto(url(itemId, first)); await expect.poll(() => fetched).toBe(true); const select = late.page.getByLabel("所选原件", { exact: true }); await select.selectOption(second.id); await expect(late.page.getByTestId("prepare-sealed")).toHaveText("准备完成 · 1 页"); await select.focus(); release(); await expect.poll(() => settled).toBe(true); await expect(select).toBeFocused(); await expect(select).toHaveValue(second.id); expect(await currentId(late.page)).toBe(secondId); await assertReadOnly(late.state, delayedBefore); } finally { release(); }
  expect(prepFacts(secondId)).toEqual(readySecond); saveEvidence("browser-discovery-boundaries", { itemId, firstDocumentId: first.id, firstPreparationId: firstId, secondDocumentId: second.id, secondPreparationId: secondId, actualPdfJs: true, totalRecordsInSecond: 22, radiosKeyboard: true, real404Retry: true, foreignAndMissingCacheRejected: true, explicitWrongPointerBlocked: true, lateFirstResponseIgnored: true, backgroundResultKeptFocus: true, readyUnchanged: true });
});
